### PR TITLE
Specsize as percentage and px for issue #259

### PR DESCRIPTION
**Pull request by phystem**
Relative width as percentage and px

### CODE REVIEW

**Comment by hypery2k** [comment]
Can one of the admins verify this patch?

**Comment by hypery2k** [comment]
Can one of the admins verify this patch?

**Comment by ishubin** [comment]
I will verify it later today.
@phystem Did you run all the tests?

**Comment by phystem** [comment]
I run only width and height tests and It is working fine

**Comment by ishubin** [comment]
Ok, I don't really remember if there are any pitfalls in tests related to percentage. Seems like it was not really covered by tests. I will retest it later today as right now I don't have time.
Please, next time if you work on a single feature send it with one pull request (right now you have two pull requests) and always run all tests before sending it. You don't need to run all tests. But at least all unit tests in galen-core project. I think they take around a minute to execute

**Comment by ishubin** [comment]
I ran all the tests and I get a lot of failures. Here are just some of them:
```
Run 45: ValidationTest.shouldGiveError:94
Expected: is <Error{["object" width is 100px instead of 10px], onlyWarn=false}>
     but: was <Error{["object" width is 100.0px instead of 10px], onlyWarn=false}>
  Run 46: ValidationTest.shouldGiveError:94
Expected: is <Error{["object" width is 100px but it should be greater than 110px], onlyWarn=false}>
     but: was <Error{["object" width is 100.0px but it should be greater than 110px], onlyWarn=false}>
  Run 47: ValidationTest.shouldGiveError:94
Expected: is <Error{["object" width is 100px but it should be less than 90px], onlyWarn=false}>
     but: was <Error{["object" width is 100.0px but it should be less than 90px], onlyWarn=false}>
  Run 48: ValidationTest.shouldGiveError:94
Expected: is <Error{["object" width is 100px which is not in range of 10 to 40px], onlyWarn=false}>
     but: was <Error{["object" width is 100.0px which is not in range of 10 to 40px], onlyWarn=false}>
  Run 49: ValidationTest.shouldGiveError:94
Expected: is <Error{["object" width is 100px instead of 20px], onlyWarn=false}>
     but: was <Error{["object" width is 50.000000% [100.0px] instead of 10% [Range{20px}]], onlyWarn=false}>
  Run 50: ValidationTest.shouldGiveError:94
Expected: is <Error{["object" width is 100px which is not in range of 20 to 40px], onlyWarn=false}>
     but: was <Error{["object" width is 50.000000% [100.0px] which is not in range of 10 to 20% [Range{20 to 40px}]], onlyWarn=false}>
```

And these ones:
```
Expected: is "<o header>\n<SpecHeight header>\n<e><msg>\"header\" height is 140px which is not in range of 150 to 185px</msg></e>\n</o header>\n<o header-text-1>\n<SpecInside header-text-1>\n</o header-text-1>\n<o menu>\n<SpecWidth menu>\n<e><msg>\"menu\" width is 410px instead of 400px</msg></e>\n</o menu>\n"
     but: was "<o header>\n<SpecHeight header>\n<e><msg>\"header\" height is 140.0px which is not in range of 150 to 185px</msg></e>\n</o header>\n<o header-text-1>\n<SpecInside header-text-1>\n</o header-text-1>\n<o menu>\n<SpecWidth menu>\n<e><msg>\"menu\" width is 102.500000% [410.0px] instead of 100% [Range{400px}]</msg></e>\n</o menu>\n"
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
	at net.mindengine.galen.tests.action.GalenPageActionCheckTest.runsTestSuccessfully_andExcludesSpecifiedTags(GalenPageActionCheckTest.java:92)

runsTestSuccessfully_inPredefinedBrowser(net.mindengine.galen.tests.action.GalenPageActionCheckTest)  Time elapsed: 0.357 sec  <<< FAILURE!
java.lang.AssertionError: Invokations should be
Expected: is "<o header>\n<SpecHeight header>\n<e><msg>\"header\" height is 140px which is not in range of 150 to 185px</msg></e>\n</o header>\n<o header-text-1>\n<SpecInside header-text-1>\n</o header-text-1>\n<o menu>\n<SpecWidth menu>\n<e><msg>\"menu\" width is 410px instead of 400px</msg></e>\n</o menu>\n<o menu>\n<SpecBelow menu>\n<SpecVertically menu>\n</o menu>\n"
     but: was "<o header>\n<SpecHeight header>\n<e><msg>\"header\" height is 140.0px which is not in range of 150 to 185px</msg></e>\n</o header>\n<o header-text-1>\n<SpecInside header-text-1>\n</o header-text-1>\n<o menu>\n<SpecWidth menu>\n<e><msg>\"menu\" width is 102.500000% [410.0px] instead of 100% [Range{400px}]</msg></e>\n</o menu>\n<o menu>\n<SpecBelow menu>\n<SpecVertically menu>\n</o menu>\n"
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
	at net.mindengine.galen.tests.action.GalenPageActionCheckTest.runsTestSuccessfully_inPredefinedBrowser(GalenPageActionCheckTest.java:57)

shouldGiveError(net.mindengine.galen.tests.validation.ValidationTest)  Time elapsed: 0.001 sec  <<< FAILURE!
java.lang.AssertionError:
Expected: is <Error{["object" width is 100px instead of 10px], onlyWarn=false}>
     but: was <Error{["object" width is 100.0px instead of 10px], onlyWarn=false}>
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:8)
	at net.mindengine.galen.tests.validation.ValidationTest.shouldGiveError(ValidationTest.java:94)

shouldGiveError(net.mindengine.galen.tests.validation.ValidationTest)  Time elapsed: 0.001 sec  <<< FAILURE!
java.lang.AssertionError:
Expected: is <Error{["object" width is 100px but it should be greater than 110px], onlyWarn=false}>
     but: was <Error{["object" width is 100.0px but it should be greater than 110px], onlyWarn=false}>
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:8)
	at net.mindengine.galen.tests.validation.ValidationTest.shouldGiveError(ValidationTest.java:94)

shouldGiveError(net.mindengine.galen.tests.validation.ValidationTest)  Time elapsed: 0 sec  <<< FAILURE!
java.lang.AssertionError:
Expected: is <Error{["object" width is 100px but it should be less than 90px], onlyWarn=false}>
     but: was <Error{["object" width is 100.0px but it should be less than 90px], onlyWarn=false}>
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:8)
	at net.mindengine.galen.tests.validation.ValidationTest.shouldGiveError(ValidationTest.java:94)

shouldGiveError(net.mindengine.galen.tests.validation.ValidationTest)  Time elapsed: 0 sec  <<< FAILURE!
java.lang.AssertionError:
Expected: is <Error{["object" width is 100px which is not in range of 10 to 40px], onlyWarn=false}>
     but: was <Error{["object" width is 100.0px which is not in range of 10 to 40px], onlyWarn=false}>
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:8)
	at net.mindengine.galen.tests.validation.ValidationTest.shouldGiveError(ValidationTest.java:94)

shouldGiveError(net.mindengine.galen.tests.validation.ValidationTest)  Time elapsed: 0 sec  <<< FAILURE!
java.lang.AssertionError:
Expected: is <Error{["object" width is 100px instead of 20px], onlyWarn=false}>
     but: was <Error{["object" width is 50.000000% [100.0px] instead of 10% [Range{20px}]], onlyWarn=false}>
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:8)
	at net.mindengine.galen.tests.validation.ValidationTest.shouldGiveError(ValidationTest.java:94)

shouldGiveError(net.mindengine.galen.tests.validation.ValidationTest)  Time elapsed: 0.001 sec  <<< FAILURE!
java.lang.AssertionError:
Expected: is <Error{["object" width is 100px which is not in range of 20 to 40px], onlyWarn=false}>
     but: was <Error{["object" width is 50.000000% [100.0px] which is not in range of 10 to 20% [Range{20 to 40px}]], onlyWarn=false}>
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:8)
	at net.mindengine.galen.tests.validation.ValidationTest.shouldGiveError(ValidationTest.java:94)

shouldGiveError(net.mindengine.galen.tests.validation.ValidationTest)  Time elapsed: 0 sec  <<< FAILURE!
java.lang.AssertionError:
Expected: is <Error{["object" height is 50px instead of 10px], onlyWarn=false}>
     but: was <Error{["object" height is 50.0px instead of 10px], onlyWarn=false}>
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:8)
	at net.mindengine.galen.tests.validation.ValidationTest.shouldGiveError(ValidationTest.java:94)

shouldGiveError(net.mindengine.galen.tests.validation.ValidationTest)  Time elapsed: 0.001 sec  <<< FAILURE!
java.lang.AssertionError:
Expected: is <Error{["object" height is 50px which is not in range of 10 to 40px], onlyWarn=false}>
     but: was <Error{["object" height is 50.0px which is not in range of 10 to 40px], onlyWarn=false}>
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:8)
	at net.mindengine.galen.tests.validation.ValidationTest.shouldGiveError(ValidationTest.java:94)

shouldGiveError(net.mindengine.galen.tests.validation.ValidationTest)  Time elapsed: 0.001 sec  <<< FAILURE!
java.lang.AssertionError:
Expected: is <Error{["object" height is 50px instead of 20px], onlyWarn=false}>
     but: was <Error{["object" height is 25.000000% [50.0px] instead of 10% [Range{20px}]], onlyWarn=false}>
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:8)
	at net.mindengine.galen.tests.validation.ValidationTest.shouldGiveError(ValidationTest.java:94)

shouldGiveError(net.mindengine.galen.tests.validation.ValidationTest)  Time elapsed: 0 sec  <<< FAILURE!
java.lang.AssertionError:
Expected: is <Error{["object" height is 50px which is not in range of 20 to 30px], onlyWarn=false}>
     but: was <Error{["object" height is 25.000000% [50.0px] which is not in range of 10 to 15% [Range{20 to 30px}]], onlyWarn=false}>
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:8)
	at net.mindengine.galen.tests.validation.ValidationTest.shouldGiveError(ValidationTest.java:94)

```

**Comment by phystem** [comment]
I got that I printed them as floating values where the assertions are done in Integers.I'll look into that

**Comment by phystem** [comment]
`Expected: is `
`<Error{["object" height is 50px which is not in range of 20 to 30px], onlyWarn=false}>`
 `    but: was `
`<Error{["object" height is 25% [50px] which is not in range of 10 to 15% [Range{20 to 30px}]], ``onlyWarn=false}>`

I guess it is an expected behavior we have to modify the assertions

**Comment by ishubin** [comment]
I am working on it.

**Pull request merged**
