### PR TITLE
Set correct scope for powermock-reflect

### LINKED ISSUE #475: Unnecessary dependencies
Galen 2.3.2 appears to have some unnecessary dependencies in its POM. Specifically, org.powermock:powermock-reflect is compile scoped rather than test scoped.

I used the GitHub search to see what it was being used for, and discovered that Mockito and PowerMock do not appear to be referenced anywhere. So perhaps those dependencies should be completely removed.

### PR DESCRIPTION
**Pull request by hypery2k**
fixes #475

### CODE REVIEW

**Comment by ishubin** [comment]
By the way, do we really need this dependency? I thought that in the original issue the reporter stated that this is unnecessary dependency. I will test it once I get some time

**Comment by hypery2k** [comment]
you're right, power mock is not needed

**Comment by ishubin** [comment]
Thanks!

**Comment by hypery2k** [comment]
you're welcome

**Pull request merged**
