### PR TITLE
Improve Selenium Grid handling

### PR DESCRIPTION
**Pull request by hypery2k**
see for #494 and https://github.com/hypery2k/galenframework-cli/issues/43

### CODE REVIEW

**Comment by ishubin** [comment]
Could you please elaborate on this change? Why do we need selenium grid in integration tests? I don't really want to make it more complex than it is already

**Comment by hypery2k** [comment]
I thought it help as we already many grid options and also some browser specific errors

**Comment by ishubin** [comment]
I like the idea of using docker for selenium grid but it seems a little bit too much such a small test.

**Comment by hypery2k** [comment]
I've found the error for this. I will create a new PR for this

**Pull request closed without merging**
