### PR TITLE
Fix windows path error

### PR DESCRIPTION
**Pull request by hypery2k**
see #414

### CODE REVIEW

**Comment by ishubin** [comment]
@hypery2k I don't want to introduce another hack just in order to fix the hack that I have introduced earlier :)
Let me dive into it a bit later. I want to fix this problem at its core and just get rid of `.\` and `./` thing completely from the code so that it works properly in Windows and Linux

**Comment by ishubin** [comment]
I made a stupid mistake long time ago implementing this path resolving. If we keep on fixing the stuff around it - it's going to be only harder to spot and fix bugs in future.

**Comment by hypery2k** [comment]
I totally understood, but it's currently a show-stopper for my customer. Can we add this as hotfix for version 2.2.x and refactor within 2.3?

**Comment by ishubin** [comment]
@hypery2k Ok, get it. I will fix it within 2.2.x version and release it. But I want to fix it properly.

**Pull request closed without merging**
