### PR TITLE
Bugfixing for screenshots

### PR DESCRIPTION
**Pull request by hypery2k**
I've merged all of you're changes from the test groups branch

### CODE REVIEW

**Comment by hypery2k** [comment]
use the latest commit 4958097069cd0945a809bc48567735d14dfb872e is missing

**Comment by ishubin** [comment]
What is the reason for such a big code refactoring and having this "final" keyword everywhere? In this pull request I see 58 files changed and most of the changes are related to this refactoring. As for me it doesn't bring any value and is just a personal coding style. In our company we didn't have such conventions ever. For me it really is a problem merging such big pull requests as I need to review every line and make sure nothing is changed in a wrong way. Any contributor may have different view on the problem so I am always careful with each pull request. 
Also  this kind of pull requests brings troubles when merging with other features. I or you have to spend time on resolving conflicts. Lets agree just to work on features and bug fixes and not on code beautifying.

**Comment by hypery2k** [comment]
yes you're right. I will omit such refactoring in the future. Should I rewrite the my changes?

**Comment by ishubin** [comment]
Thanks for your understanding. Yes, please, that would be nice.

**Comment by hypery2k** [comment]
sure no problem ;) I will create a new pull request

**Comment by hypery2k** [comment]
see #226

**Pull request closed without merging**
