### PR TITLE
Adding chromedriver for local development

### PR DESCRIPTION
**Pull request by hypery2k**

### CODE REVIEW

**Comment by hypery2k** [comment]
Can one of the admins verify this patch?

**Comment by ishubin** [comment]
@hypery2k could you please switch off those auto-generated comments ("Can one of the admins verify this patch?") on each of your pull requests?

**Comment by hypery2k** [comment]
Can one of the admins verify this patch?

**Comment by hypery2k** [comment]
came from my jenkins server. Should be disabled for now ;)

**Comment by ishubin** [comment]
Thanks!

**Pull request merged**
