### PR TITLE
Fix file not found errors

### PR DESCRIPTION
**Pull request by hypery2k**
see #395

### CODE REVIEW

**Comment by ishubin** [comment]
Looks like your pull request fails https://travis-ci.org/galenframework/galen/jobs/108790032

**Comment by hypery2k** [comment]
Mmh ok, I will take a look at it

**Comment by ishubin** [comment]
@hypery2k I checked that issue and here is my comment https://github.com/galenframework/galen/issues/395#issuecomment-183763358

I guess the only thing we should fix in this case is adding a better error message than NullPointerException

**Comment by hypery2k** [comment]
I totally agree. I revert my additional condition and just add a LOG entry. So just removed the printstack ;)

But If you want to omit completely my changes, I can live with it ;)

**Comment by ishubin** [comment]
I would prefer to have a better mechanism of this error handling. Just wrapping it into LOG entry with some generic message - is not a solution. To be honest I am not in favor of having all the "Unknown error during <placeholder text>" in such cases. Because that doesn't give that much benefit and it will still be a NullPointerException inside.  A proper solution - not allow any NullPointerException in the code. In this particular example the NullPointerException is thrown because of some inner javascript error in client side of the browser and it doesn't return any value. So the next call `.doubleValue()` fails.  I guess we should be able to intercept that error and print it as.

Also if you look at the file changes https://github.com/galenframework/galen/pull/396/files - it is enormous amounts of code line changes which are actually useless. The only real change is just one line https://github.com/galenframework/galen/pull/396/files#diff-e3ad7555e1208f7211c8465f9e630a77R182
Lets have cleaner pull requests with only relevant commits and code line changes

**Pull request closed without merging**
