### PR TITLE
Adding JUnit report support

### PR DESCRIPTION
**Pull request by hypery2k**
see #336

### CODE REVIEW

**Comment by hypery2k** [comment]
Can one of the admins verify this patch?

**Comment by hypery2k** [comment]
Can one of the admins verify this patch?

**Comment by ishubin** [comment]
@hypery2k I checked the code changes, looks good, thanks! But I will need to test it thoroughly a bit later today. 
For now could you please change this pull request from master branch to release-2.2? This is a new feature so it should go into the next release

**Comment by hypery2k** [comment]
I'm already tested it locally and rebased against release 2.2 ;)

**Comment by ishubin** [comment]
@hypery2k github for some reason still shows me that it will merge it to master. Will try to merge it manually.

**Comment by ishubin** [comment]
I just tested it on my galen-sample-tests project and it fails:

```
Nov 03, 2015 9:58:03 PM freemarker.log.JDK14LoggerFactory$JDK14Logger error
SEVERE: Template processing error: "Expression test.testInfo.exception is undefined on line 8, column 58 in report-main."

Expression test.testInfo.exception is undefined on line 8, column 58 in report-main.
The problematic instruction:
----------
==> ${test.testInfo.exception.class.name} [on line 8, column 56 in report-main]
----------

Java backtrace for programmers:
----------
freemarker.core.InvalidReferenceException: Expression test.testInfo.exception is undefined on line 8, column 58 in report-main.
	at freemarker.core.TemplateObject.assertNonNull(TemplateObject.java:125)
	at freemarker.core.TemplateObject.invalidTypeException(TemplateObject.java:135)
	at freemarker.core.Dot._getAsTemplateModel(Dot.java:78)
	at freemarker.core.Expression.getAsTemplateModel(Expression.java:89)
	at freemarker.core.Dot._getAsTemplateModel(Dot.java:74)
	at freemarker.core.Expression.getAsTemplateModel(Expression.java:89)
	at freemarker.core.Expression.getStringValue(Expression.java:93)
	at freemarker.core.DollarVariable.accept(DollarVariable.java:76)
	at freemarker.core.Environment.visit(Environment.java:221)
	at freemarker.core.MixedContent.accept(MixedContent.java:92)
	at freemarker.core.Environment.visit(Environment.java:221)
	at freemarker.core.ConditionalBlock.accept(ConditionalBlock.java:79)
	at freemarker.core.Environment.visit(Environment.java:221)
	at freemarker.core.MixedContent.accept(MixedContent.java:92)
	at freemarker.core.Environment.visit(Environment.java:221)
	at freemarker.core.IteratorBlock$Context.runLoop(IteratorBlock.java:179)
	at freemarker.core.Environment.visit(Environment.java:428)
	at freemarker.core.IteratorBlock.accept(IteratorBlock.java:102)
	at freemarker.core.Environment.visit(Environment.java:221)
	at freemarker.core.MixedContent.accept(MixedContent.java:92)
	at freemarker.core.Environment.visit(Environment.java:221)
	at freemarker.core.Environment.process(Environment.java:199)
	at freemarker.template.Template.process(Template.java:259)
	at com.galenframework.reports.JunitReportBuilder.exportJunitReport(JunitReportBuilder.java:58)
	at com.galenframework.reports.JunitReportBuilder.build(JunitReportBuilder.java:45)
	at com.galenframework.actions.GalenActionTest.createJunitReport(GalenActionTest.java:271)
	at com.galenframework.actions.GalenActionTest.createAllReports(GalenActionTest.java:243)
	at com.galenframework.actions.GalenActionTest.runTestsInThreads(GalenActionTest.java:144)
	at com.galenframework.actions.GalenActionTest.runTests(GalenActionTest.java:115)
	at com.galenframework.actions.GalenActionTest.runTestFiles(GalenActionTest.java:106)
	at com.galenframework.actions.GalenActionTest.execute(GalenActionTest.java:85)
	at com.galenframework.GalenMain.execute(GalenMain.java:58)
	at com.galenframework.GalenMain.main(GalenMain.java:78)

[main] ERROR com.galenframework.actions.GalenActionTest - Unknown error during creating Junit report.

Expression test.testInfo.exception is undefined on line 8, column 58 in report-main.
The problematic instruction:
----------
==> ${test.testInfo.exception.class.name} [on line 8, column 56 in report-main]
----------

Java backtrace for programmers:
----------
freemarker.core.InvalidReferenceException: Expression test.testInfo.exception is undefined on line 8, column 58 in report-main.
	at freemarker.core.TemplateObject.assertNonNull(TemplateObject.java:125)
	at freemarker.core.TemplateObject.invalidTypeException(TemplateObject.java:135)
	at freemarker.core.Dot._getAsTemplateModel(Dot.java:78)
	at freemarker.core.Expression.getAsTemplateModel(Expression.java:89)
	at freemarker.core.Dot._getAsTemplateModel(Dot.java:74)
	at freemarker.core.Expression.getAsTemplateModel(Expression.java:89)
	at freemarker.core.Expression.getStringValue(Expression.java:93)
	at freemarker.core.DollarVariable.accept(DollarVariable.java:76)
	at freemarker.core.Environment.visit(Environment.java:221)
	at freemarker.core.MixedContent.accept(MixedContent.java:92)
	at freemarker.core.Environment.visit(Environment.java:221)
	at freemarker.core.ConditionalBlock.accept(ConditionalBlock.java:79)
	at freemarker.core.Environment.visit(Environment.java:221)
	at freemarker.core.MixedContent.accept(MixedContent.java:92)
	at freemarker.core.Environment.visit(Environment.java:221)
	at freemarker.core.IteratorBlock$Context.runLoop(IteratorBlock.java:179)
	at freemarker.core.Environment.visit(Environment.java:428)
	at freemarker.core.IteratorBlock.accept(IteratorBlock.java:102)
	at freemarker.core.Environment.visit(Environment.java:221)
	at freemarker.core.MixedContent.accept(MixedContent.java:92)
	at freemarker.core.Environment.visit(Environment.java:221)
	at freemarker.core.Environment.process(Environment.java:199)
	at freemarker.template.Template.process(Template.java:259)
	at com.galenframework.reports.JunitReportBuilder.exportJunitReport(JunitReportBuilder.java:58)
	at com.galenframework.reports.JunitReportBuilder.build(JunitReportBuilder.java:45)
	at com.galenframework.actions.GalenActionTest.createJunitReport(GalenActionTest.java:271)
	at com.galenframework.actions.GalenActionTest.createAllReports(GalenActionTest.java:243)
	at com.galenframework.actions.GalenActionTest.runTestsInThreads(GalenActionTest.java:144)
	at com.galenframework.actions.GalenActionTest.runTests(GalenActionTest.java:115)
	at com.galenframework.actions.GalenActionTest.runTestFiles(GalenActionTest.java:106)
	at com.galenframework.actions.GalenActionTest.execute(GalenActionTest.java:85)
	at com.galenframework.GalenMain.execute(GalenMain.java:58)
	at com.galenframework.GalenMain.main(GalenMain.java:78)
There were failures in galen tests
```

**Comment by ishubin** [comment]
Nevermind, I found the problem and fixed it :)

**Comment by ishubin** [comment]
Merged it into release-2.2

**Pull request closed without merging**
