### PR TITLE
Bugfixing

### PR DESCRIPTION
**Pull request by hypery2k**

### CODE REVIEW

**Comment by ishubin** [comment]
Thanks! I will merge this pull request. But please next time don't commit the things specific to your formatter IDE (this one https://github.com/hypery2k/galen/commit/fc2fe2cce3d9561359bc5da1c6255b00f057c30f). It just doesn't bring any value to the project and is basically just your own setting. Also it makes it harder to track stuff in git history when investigating issues.

**Comment by hypery2k** [comment]
this is not IDE specific, it works in IDEA also. It just prevent that the auto formatter formats this area.

But I can omit such things

**Comment by ishubin** [comment]
Oh, ok. I just never used auto-formatter in Intellij so not aware of this things

**Comment by hypery2k** [comment]
I've often just this in enums or within builders. because there manually formatter code is really more readable ;)

**Pull request closed without merging**
