### PR TITLE
Improve Java Integration

### PR DESCRIPTION
**Pull request by hypery2k**
During writing Java-based tests at the customer with JUnit I experienced some issue and here are some fixes for that.

### CODE REVIEW

**Comment by hypery2k** [comment]
Can one of the admins verify this patch?

**Comment by hypery2k** [comment]
Can one of the admins verify this patch?

**Comment by hypery2k** [comment]
The fix for the JUnit-Changes is an important bugfix to resolve issues running Galen-based JUnit-Tests

**Comment by ishubin** [comment]
@hypery2k Thanks for your pull request. I wanted to do something like that long time ago. The only thing - I decided to change the error message. Here is an example of exception:

```
com.galenframework.support.LayoutValidationException: galen-sample-js-project/specs/welcomePage.gspec, tags: [desktop]
  - Child component spec contains 2 errors (galen-sample-js-project/specs/common.gspec:18)
    - "logo" is 13px top instead of 100px (galen-sample-js-project/specs/header-component.gspec:7)
    - "logo" width is 48px instead of 100px (galen-sample-js-project/specs/header-component.gspec:8)
  - "header" height is 109px which is not in range of 68 to 72px (galen-sample-js-project/specs/common.gspec:21)
  - "header.text" text is "Sample Website for Galen Framework (has bugs :))" but should be "Sample Website for Galen Framework" (galen-sample-js-project/specs/common.gspec:35)
  - "menu.item-2" is not aligned horizontally all with "menu.item-3". Offset is 2px (galen-sample-js-project/specs/common.gspec:68)
  - "menu.item-3" is not aligned horizontally all with "menu.item-4". Offset is 2px (galen-sample-js-project/specs/common.gspec:68)


	at com.galenframework.support.GalenJavaTestBase.checkLayout(GalenJavaTestBase.java:126)
	at com.galenframework.support.GalenJavaTestBase.checkLayout(GalenJavaTestBase.java:108)
	at com.galenframework.tests.integration.TempTestIT.shouldCheckLayout(TempTestIT.java:23)
```

**Comment by hypery2k** [comment]
very cool ;) I like it. Thanks

**Pull request merged**
