### PR TITLE
Improve code quality

### PR DESCRIPTION
**Pull request by hypery2k**

### CODE REVIEW

**Comment by ishubin** [comment]
I have ran all the tests and I got errors in 3 tests related to console reporting. Just run the tests in ReportingTest class.
shouldReport_toConsole_onlySuites_andPages_whenLogLevel_is_2(net.mindengine.galen.tests.runner.ReportingTest)
shouldReport_toConsole_successfully(net.mindengine.galen.tests.runner.ReportingTest)
shouldReport_toConsole_onlySuites_whenLogLevel_is_1(net.mindengine.galen.tests.runner.ReportingTest)

**Comment by hypery2k** [comment]
I will take a look to theses tests

**Comment by hypery2k** [comment]
I moved to the previous version without logger and the tests are working again, but some tests are still failing:
shouldImport_otherSpecs_fromOtherFiles(net.mindengine.galen.tests.specs.reader.PageSpecsReaderTest): (..)
  shouldCheck_relativeToViewport(net.mindengine.galen.tests.selenium.GalenSeleniumTest): Invokations should(..)
  performsValidation_forAll(net.mindengine.galen.tests.selenium.GalenSeleniumTest): Invokations should(..)

More details at: https://martinreinhardt-online.de/jenkins/job/GalenFramework_build_fork/lastBuild/testReport/

**Comment by ishubin** [comment]
For me all the tests are passed. I have merged your pull request with the latest changes and everything was green. But the tests you mentioned - are flickering and are using the FirefoxDriver. This is something I was telling you about. We should move at some point all the tests to a used a mocked WebDriver. This is the component I am using from now on for all tests that need a WebDriver - net.mindengine.galen.components.mocks.driver.MockedDriver

**Comment by hypery2k** [comment]
ok, I see. maybe we should change to this WebDriver within the tests to ensure they are up and running

**Pull request merged**
