### PR TITLE
Adding selenium version info to version output

### PR DESCRIPTION
**Pull request by hypery2k**
Referring to  #272 and confusing by some [users](https://groups.google.com/forum/#!topic/galen-framework/m5u64Br4_QQ)

So this PR will change the output of version info:
```bash
$ galen --version
Galen Framework
Version: 2.0.5
JavaScript executor: Rhino 1.7 release 5 2015 01 29
Selenium version: 2.46.0
```

### CODE REVIEW

**Comment by ishubin** [comment]
It doesn't work when I assemble and install a binary:
```
$ galen -v
Galen Framework
Version: 2.0.6
JavaScript executor: Rhino 1.7 release 5 2015 01 29
Selenium version:
```

**Comment by ishubin** [comment]
And by the way, why does VersionUtil has to be so complex? We can easily get all the information from ```/META-INF/maven/org.seleniumhq.selenium/selenium-java/pom.properties```

Here is the working code:

```
System.out.println(IOUtils.toString(GalenMain.class.getResourceAsStream("/META-INF/maven/org.seleniumhq.selenium/selenium-java/pom.properties")));
```

**Comment by hypery2k** [comment]
you're right, that's far better ;)

I've changed it in the PR

**Comment by ishubin** [comment]
Ok, I have few points:
* lets make this change in a separate pull request so that we have a clean history without that VersionUtil.
* As for the code I gave in my previous comment - it is actually wrong. Sorry forgot to mention that it prints multiple properties of the selenium artifact and you actually have to parse it as a property file.

Here is what it prints:
```
#Generated by Maven
#Thu Jul 30 10:46:09 PDT 2015
version=2.47.1
groupId=org.seleniumhq.selenium
artifactId=selenium-java
```

We just need to extract the "version" property out of it and only print it without the other properties.
Also I think it would be nice to have a unit test that checks that this selenium version is returned correctly (I think the regex assertion is enough).

**Pull request closed without merging**
