### PR TITLE
Simplify selenium dependencies

### PR DESCRIPTION
**Pull request by fhoeben**
Instead of galen-core having multiple explicit dependencies on selenium libraries this pull request changes that to a single one (`selenium-java`) which was already present and has all others as transative dependencies. Less code, same result.

When other project's depend on this project having a single dependency makes it easier to manage that dependency (and ensure they all use the same selenium version). For instance via 'dependencyManagement' or 'exclusions' one can then limit it to `selenium-java` instead of having to do each one...

### CODE REVIEW

**Comment by ishubin** [comment]
Looks like it doesn't work. There are failures in integration tests https://travis-ci.org/galenframework/galen/builds/301409430#L3926
`Could not initialize class org.openqa.selenium.json.Json`

**Comment by fhoeben** [comment]
I think (hope?) that was caused by other troubles in the branch I based my pull request of.

I rebased onto current master and now I get different unit test errors. Locally Maven still reports success.
The log of the build in travis seems to be full of errors also, but overall success is reported.

Does this mean the change is ok now?

**Comment by hypery2k** [comment]
seems okay now

**Comment by ishubin** [comment]
Weird, this pull request shows very strange diffs. Something is messed up with merges. I will review it later today

**Comment by fhoeben** [comment]
Probably something to do with that I started of release2.4 branch and later merged in master. The change is really simple (should only be commit 57882e4d6529794c66f9549c6e6599cddc93c5eb). Should I make a new pull request to just highlight that?

**Comment by ishubin** [comment]
Yes @fhoeben , please do that. It will make it easier for me :)

**Comment by fhoeben** [comment]
Replaced by #532

**Pull request closed without merging**
