### PR TITLE
Improve code quality

### PR DESCRIPTION
**Pull request by hypery2k**
* wrap up the runtime exceptions
* cleaning up code
* implemented some TODO's

### CODE REVIEW

**Comment by hypery2k** [comment]
Can one of the admins verify this patch?

**Comment by hypery2k** [comment]
Can one of the admins verify this patch?

**Comment by ishubin** [comment]
Thanks! I am going to merge your pull request. The only thing I would like to note: please don't do big code improvements/cleanup on the stuff in general. Especially on my own code. The thing is we have a different coding style with you and I don't see a lot of sense on changing the code back and forth. I prefer to do the big refactoring and cleanup on my own as I have a lot of things planned already and I know which components are going to be thrown away and which ones will be used in future differently. For instance the cleanup on PageSpecReader is not needed at all as I am planning to physically remove this file when I migrate all the spec processing to a new syntax. The same way might go away a lot of other files related to old spec processing. Also I might introduce a lot of changes to test suite processor.

At the same time I am also not going to touch your code (JUnit and TestNG runners) unless I am fixing a bug in it or changing the functionality. I think you are doing a good job in programming but I have different opinion about the style. 

For instance I always try to put single statement in the brackets in the else block instead of one-liner. That makes it easier for me to parse the logical statements with my own eyes when I quickly go through the code. For the same reason I try to avoid ternary operator as it makes the code less readable. I would rather wrap it in a properly named method instead of having complex one-liner. Also I am not in favor of declaring general exceptions on each method (e.g. SetupException). In my mind those could be just RuntimeException or IllegalArgumentException so there is no much sense of declaring them.

I hope you don't find me too criticizing. There are two major reasons I am against big code cleanups:
    1. If it was done by a different person - for me later it makes it a bit harder to dive into the code
    2. It makes it hard to do "git blame" when you analyze the root cause of an issue. Quite often I have do to it, when researching around the bug.

**Comment by hypery2k** [comment]
Okay, your right and it's one to be open ;)

Next time I'll chat in gitter and we can discuss real changes like exception handling

The coding style think I will respect ;)

**Comment by ishubin** [comment]
Thanks :+1:

**Comment by hypery2k** [comment]
No problem. Still learning how to participate in an open source project

**Comment by ishubin** [comment]
To be honest for me it is also a learning curve as it is the first project where I review and accept pull requests. I am not really that kind of person that likes managing others work. Especially when it comes to rejecting.

**Pull request merged**
