### PR TITLE
Improve code quality

### PR DESCRIPTION
**Pull request by hypery2k**
see #189

### CODE REVIEW

**Comment by hypery2k** [comment]
added formatter and JSlint
added also proper logging via SLF4J (needs to be improved in the existing code too)

**Comment by ishubin** [comment]
Hi Martin!
I get compilation errors in your pull request when running 'mvn clean test':

[ERROR] COMPILATION ERROR :
[INFO] -------------------------------------------------------------
[ERROR] /Users/ishubin/workspace/my/galen/src/main/java/net/mindengine/galen/javascript/JsFunctionLoad.java:[30,28] error: package org.testng.log4testng does not exist
[ERROR] /Users/ishubin/workspace/my/galen/src/main/java/net/mindengine/galen/javascript/JsFunctionLoad.java:[34,23] error: cannot find symbol
[ERROR]  class JsFunctionLoad
/Users/ishubin/workspace/my/galen/src/main/java/net/mindengine/galen/reports/HtmlReportBuilder.java:[39,28] error: package org.testng.log4testng does not exist
[ERROR] /Users/ishubin/workspace/my/galen/src/main/java/net/mindengine/galen/reports/HtmlReportBuilder.java:[47,23] error: cannot find symbol
[ERROR]  class HtmlReportBuilder
/Users/ishubin/workspace/my/galen/src/main/java/net/mindengine/galen/runner/EventHandler.java:[21,28] error: package org.testng.log4testng does not exist
[ERROR] /Users/ishubin/workspace/my/galen/src/main/java/net/mindengine/galen/runner/EventHandler.java:[31,23] error: cannot find symbol
[ERROR]  class EventHandler
/Users/ishubin/workspace/my/galen/src/main/java/net/mindengine/galen/GalenMain.java:[59,28] error: package org.testng.log4testng does not exist
[ERROR] /Users/ishubin/workspace/my/galen/src/main/java/net/mindengine/galen/GalenMain.java:[63,23] error: cannot find symbol
[ERROR]  class GalenMain
/Users/ishubin/workspace/my/galen/src/main/java/net/mindengine/galen/validation/specs/SpecValidationImage.java:[37,28] error: package org.testng.log4testng does not exist
[ERROR] /Users/ishubin/workspace/my/galen/src/main/java/net/mindengine/galen/validation/specs/SpecValidationImage.java:[41,23] error: cannot find symbol
[ERROR]  class SpecValidationImage
/Users/ishubin/workspace/my/galen/src/main/java/net/mindengine/galen/javascript/JsFunctionLoad.java:[34,36] error: cannot find symbol
[ERROR]  class JsFunctionLoad
/Users/ishubin/workspace/my/galen/src/main/java/net/mindengine/galen/reports/HtmlReportBuilder.java:[47,36] error: cannot find symbol
[ERROR]  class HtmlReportBuilder
/Users/ishubin/workspace/my/galen/src/main/java/net/mindengine/galen/runner/EventHandler.java:[31,36] error: cannot find symbol
[ERROR]  class EventHandler
/Users/ishubin/workspace/my/galen/src/main/java/net/mindengine/galen/GalenMain.java:[63,36] error: cannot find symbol
[ERROR]  class GalenMain
/Users/ishubin/workspace/my/galen/src/main/java/net/mindengine/galen/validation/specs/SpecValidationImage.java:[41,36] error: cannot find symbol
[INFO] 15 errors
[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 3.187s
[INFO] Finished at: Tue Jan 13 11:38:56 CET 2015
[INFO] Final Memory: 18M/491M

**Comment by ishubin** [comment]
Also I see you have changed a lot of lines because of indentation with 2 spaces instead of 4. Could you please change the formatter to 4 spaces? 
I normally don't mind about the amount of spaces but in this case it makes it hard to see what was really changed in the code. Because I just get a vary big page which I have to scroll through. Lets just stick to 4 spaces for now.

**Comment by hypery2k** [comment]
ok, I've changed it. 
Maybe it would be good to do a initial code formatting to make it easier for you to see changes by us.

**Comment by ishubin** [comment]
Thanks, I will test it a bit later

**Comment by ishubin** [comment]
@hypery2k  I only now had the chance to test all your changes. Now everything works. The tests are passed. But I see that in the code you have changed System.out.println to LOG.info. In some cases that is ok but in some cases I am against it as it prints a lot of useless information on the screen. Here is what I get when I execute "galen --version":

```
[main] INFO net.mindengine.galen.GalenMain - Galen Framework
[main] INFO net.mindengine.galen.GalenMain - Version: 1.4.11
```

But it doesn't make any sense for me. As a regular user I would like just to get this like in any other program:
```
Galen Framework
Version: 1.4.11
```
Also I see that you have added logging of exceptions in catch blocks in SpecValidationImage class. That also is not needed for the end user as these errors will be anyway rendered in the reports. The console output of galen should be as clean as possible. 
Do you really need this in your project? If yes then lets discuss how we can make it work for everyone.

**Comment by ishubin** [comment]
I can just merge your change and fix these things myself. But I would like to understand your intention and maybe come up with something else

**Comment by hypery2k** [comment]
oh I see your point, I've changed the logging slightly. Hope that okay right now.
I've changed the logging to trace within the SpecValidationImage class

**Comment by ishubin** [comment]
Thanks! Merged all your changes into release-1.5 branch

**Pull request merged**
