### PR TITLE
Test and improve GalenJUnitTestBase

### PR DESCRIPTION
**Pull request by stefanbirkner**

### CODE REVIEW

**Comment by hypery2k** [comment]
Can one of the admins verify this patch?

**Comment by ishubin** [comment]
That's not really a big difference. What I wanted to say is that doing some logic based on stacktrace is very bad design. Unfortunately I am not a big fan of JUnit and have little experience with it. In TestNG there is always a way to get detailed information about test method in "before" and "after" events. 
Taking the name of the method from stacktrace - is a hack which I would like to avoid

**Comment by ishubin** [comment]
Here is a line from TestNG documentation:

```
Any @BeforeMethod (and @AfterMethod) can declare a parameter of type java.lang.reflect.Method. This parameter will receive the test method that will be called once this @BeforeMethod finishes (or after the method as run for @AfterMethod).
```

Isn't there anything similar in JUnit?

**Comment by hypery2k** [comment]
**JUnit 4.7.x - 4.8.x**
The following approach will print method names for all tests in a class:
```java
@Rule
public MethodRule watchman = new TestWatchman() {
   public void starting(FrameworkMethod method) {
      System.out.println("Starting test: " + method.getName());
   }
};
```

**JUnit 4.9.x onwards**
Since JUnit 4.9, the TestWatchman class has been deprecated in favour of the TestWatcher class, which has a similar invocation:
```java
@Rule
public TestRule watcher = new TestWatcher() {
   protected void starting(Description description) {
      System.out.println("Starting test: " + description.getMethodName());
   }
};
```

**Comment by ishubin** [comment]
@hypery2k Thanks! Will investigate that as part of #362 story.

**Comment by hypery2k** [comment]
i think we can use the 4.9 behavior as 4.12 is already released ;)

**Comment by ishubin** [comment]
agree, lets check it

**Comment by stefanbirkner** [comment]
@ishubin Do you want to merge this branch nevertheless. It has three other commits that improve the current the code. Although getting the name from the stacktrace is not the final solution, not creating an exception is better than what we have now.

Otherwise I could create a new pull request without the last commit.

**Comment by hypery2k** [comment]
Can one of the admins verify this patch?

**Comment by ishubin** [comment]
@hypery2k Please switch that thing off

**Comment by ishubin** [comment]
It becomes quite annoying to receive emails for auto-generated github comments

**Comment by ishubin** [comment]
I am going to merge this pull request but in release-2.3 branch

**Comment by hypery2k** [comment]
I hope I switched it off now. Sorry missed one Jenkins config entry

**Comment by ishubin** [comment]
Thanks!

**Comment by ishubin** [comment]
@stefanbirkner I merged it in release-2.3 branch. Please for future improvements like this send pull requests to the release branch. I am using master for current version bug-fixes and readme updates only. Anything new should go into release branch and it will be merged with master branch at the day of the release

**Pull request closed without merging**
