### PR TITLE
Improve JUnit/TestNG runners

### PR DESCRIPTION
**Pull request by hypery2k**
I've just improved the TestNG and JUnit integration slightly, see #117

### CODE REVIEW

**Comment by hypery2k** [comment]
Maybe the quit driver should use: @AfterClass(alwaysRun = true) to avoid recreating drivers for each test run

**Comment by ishubin** [comment]
Isn't the ```GalenJUnitTestBase``` a copy paste of ```GalenTestNgTestBase```? Why not move all the code in the base class for these both classes?

**Comment by hypery2k** [comment]
good point, I can do this. What do you think about the @AfterClass thing?

**Comment by ishubin** [comment]
I don't think there is a benefit of moving it to after class event. Because then that would mean that instantiation of webdriver should also be moved to before class event. And we do so then running test methods in parallel would not be possible.

**Pull request merged**
