### PR TITLE
Improve stability of tests

### PR DESCRIPTION
**Pull request by hypery2k**

### CODE REVIEW

**Comment by ishubin** [comment]
I have merged it locally with release-1.6 branch and all the Java TestNG tests are passed. But in the end I get:

```
[INFO] 
[INFO] Execution Time (2015-01-31 08:54:21 UTC)
[INFO] loading tasks    8ms  ▇▇▇▇ 7%
[INFO] mochaTest:test  73ms  ▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇ 65%
[INFO] jslint:client   31ms  ▇▇▇▇▇▇▇▇▇▇▇▇▇ 27%
[INFO] Total 113ms
[INFO] 
[INFO] ------------------------------------------------------------------------
[ERROR] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Failed to run task
[INFO] ------------------------------------------------------------------------
[INFO] For more information, run Maven with the -e switch
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 1 minute 16 seconds
[INFO] Finished at: Sat Jan 31 09:54:21 CET 2015
[INFO] Final Memory: 53M/518M
[INFO] ------------------------------------------------------------------------
```

Does it fail because of jslint errors?

**Comment by ishubin** [comment]
I am going to fix all these jslint complains. If it fails the build because of this, then this is awesome

**Comment by hypery2k** [comment]
yes it fails because of jslint ;)

**Comment by ishubin** [comment]
Oh, then it is super cool. Will force to write proper JavaScript :)
Thanks!

**Comment by hypery2k** [comment]
no problem. I love the simple maven frontend plugin. Helps to bring grunt and maven nicely together and you still can use both tools ;)

**Pull request merged**
